<section id="admin-message">
    <div class="admin-menu">
        <a href="admin.php"><i class="fas fa-angle-double-left"></i>Menu Admin</a>
    </div>
    <h1 class="title">Message</h1>
    <ul class="user-message">
        <li><span>De&nbsp;: </span> <span> Prénom Nom</span></li>
        <li><span>Reçu le&nbsp;: </span> <span>date</span></li>
        <li><span>Sujet&nbsp;: </span> <span>sujet</span></li>
        <li><span>Message&nbsp;: </span> <span>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquid atque unde facere doloribus laborum placeat voluptatum, cum est commodi voluptate dicta. Quaerat, fuga suscipit? Provident dolor velit natus quibusdam quidem.</span></li>
    </ul>
    <div class="message-btn">
        <a href="mailto:mailuser@user.com"><i class="fas fa-envelope"></i>Répondre à Prénom Nom</a>
        <a data-action="remove" href=""><i class="fa fa-trash"></i>Supprimer</a>
    </div>
    <div class="admin-menu">
        <a href="admin.php"><i class="fas fa-angle-double-left"></i>Menu Admin</a>
    </div>
</section>