<section id="admin-login">
    <form action="" method="post">
        <fieldset>
            <legend>Connexion Admin</legend>
            <ul>
                <li>
                    <label>Votre identifiant : </label>
                    <input type="text" name="id">
                </li>
                <li>
                    <label>Votre mot de passe : </label>
                    <input type="password" name="password">
                </li>
            </ul>
            <button class="admin-btn" type="submit" name="connexion" ><i class="fas fa-user-circle"></i>Connexion</button>
        </fieldset>
    </form>
</section>