<section id="admin">
    <section class="admin-messages">
        <h1 class="title">Mes messages</h1>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Heure</th>
                    <th class="hidden">Civilité</th>
                    <th>Nom</th>
                    <th class="hidden">Prénom</th>
                    <th class="hidden">Code Postal</th>
                    <th class="hidden">Ville</th>
                    <th>Sujet</th>
                    <th class="hidden">Message</th>
                </tr>
            </thead>
            <tbody id="tbody-message">
                <?php foreach($messages as $message): ?>            
                    <tr>  <!-- on précise onclick a chaque ligne plutot qu'au <tr> parce que ca pose probleme pour le lien <a> (qui ,de ce fait, n'a pas le onclick !) avec l'icone de la poubelle qui permet la suppression en AJAX -->
                <!-- date d'envoi -->
                        <td class="onclick-msg" data-id="<?= intval($message['id'])?>"><?= $message['sendingday']?> <?= $months[($message['sendingmonth'])-1]?> <?= $message['sendingyear']?></td>
                <!-- heure d'envoi -->
                        <td class="onclick-msg" data-id="<?= intval($message['id'])?>"><?= $message['sendingtime']?></td>
                <!-- Mme ou M. -->
                        <td class="onclick-msg hidden" data-id="<?= intval($message['id'])?>"><?= $message['gender']?></td>
                <!-- Nom de famille -->
                        <td class="onclick-msg" data-id="<?= intval($message['id'])?>"><?= substr($message['lastname'],0,10);?></td>
                <!-- Prénom -->
                        <td class="onclick-msg hidden" data-id="<?= intval($message['id'])?>"><?= substr($message['firstname'],0,10);?></td>
                <!-- code Postal -->
                        <td class="onclick-msg hidden" data-id="<?= intval($message['id'])?>"><?= $message['zipcode']?></td>
                <!-- Ville -->
                        <td class="onclick-msg hidden" data-id="<?= intval($message['id'])?>"><?= substr($message['city'],0,17);?></td>
                <!-- Sujet du message -->
                        <td class="onclick-msg" data-id="<?= intval($message['id'])?>"><?= $message['subjectmessage']?></td>
                <!-- Message -->
                        <td class="onclick-msg hidden" data-id="<?= intval($message['id'])?>"><?= substr($message['usermessage'],0,20);?></td>
                <!-- Bouton de suppression du message -->
                        <td class="hidden"><a class="remove" data-choice="message" data-remove="<?= intval($message['id'])?>" href="admin?delete_message=<?= intval($message['id'])?>"><i class="fa fa-trash"></i></a></td>
                    </tr>
                <?php endforeach; ?>
                
            </tbody>
        </table>

    </section>

    <section class="admin-news-events">
        <h2 class="title">Mes Prochains Evénements</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="hidden">Heure de début</th>
                    <th class="hidden">Heure de fin</th>
                    <th>Lieu</th>
                    <th>Evenement</th>
                    <th>Description</th>
                </tr>
            </thead>

            <tbody id="tbody-event">
                <?php foreach($newsEvents as $newsEvent): ?>
                    <tr>
                        <td class="onclick-event" data-id="<?= intval($newsEvent['id'])?>"><?= $newsEvent['eventday']?> <?php if($newsEvent['eventmonth'] != null) echo $months[($newsEvent['eventmonth'])-1]?> <?= $newsEvent['eventyear']?></td>
                        <td class="onclick-event hidden" data-id="<?= intval($newsEvent['id'])?>"><?= $newsEvent['eventtime']?></td>
                        <td class="onclick-event hidden" data-id="<?= intval($newsEvent['id'])?>"><?= $newsEvent['endtime']?></td>
                        <td class="onclick-event" data-id="<?= intval($newsEvent['id'])?>"><?= substr($newsEvent['city'],0,15);?></td>
                        <td class="onclick-event" data-id="<?= intval($newsEvent['id'])?>"><?= substr($newsEvent['eventtype'],0,15);?></td>
                        <td class="onclick-event" data-id="<?= intval($newsEvent['id'])?>"><?= substr($newsEvent['eventdescription'],0,30);?></td>
                        <td class="hidden">
                            <div>
                                <a href="myevents?update_event=<?= intval($newsEvent['id'])?>">
                                <i class="fa fa-edit"></i></a>

                                <a class="remove" data-choice="event" data-remove="<?= intval($newsEvent['id'])?>" href="admin?delete_event=<?= intval($newsEvent['id'])?>">
                                <i class="fa fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <a class="admin-a-btn" href="myevents"><i class="fas fa-plus"></i> Ajouter un événement</a>
    </section>

    <section class="admin-products">
        <h2 class="title">Mes Produits affichés sur le site</h2>
        <table>
            <thead>
                <tr>
                    <th>Réf Produit</th>
                    <th>Catégorie</th>
                    <th>Titre</th>
                </tr>
            </thead>
            <tbody id="tbody-product">
                <?php foreach($products as $product): ?>
                    <tr>
                        <td class="onclick-product" data-id="<?= intval($product['id'])?>"><?= $product['ref']?></td>
                        <td class="onclick-product" data-id="<?= intval($product['id'])?>"><?= $product['category']?></td>
                        <td class="onclick-product" data-id="<?= intval($product['id'])?>"><?= $product['title']?></td>
                        <td>
                            <a href="myproducts?update_product=<?= intval($product['id'])?>"><i class="fa fa-edit"></i></a>
                            <a class="remove" data-choice="product" data-remove="<?= intval($product['id'])?>" href="admin?delete_product=<?= intval($product['id'])?>"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <a class="admin-a-btn" href="myproducts"><i class="fas fa-plus"></i> Ajouter un produit</a>
    </section>
    
    <form class="logout-btn" action="log" method="post">
        <button class="admin-btn" name="logout" type="submit"><i class="fas fa-sign-out-alt"></i>Déconnexion</button>
    <form>

    <a class="update-login" href="updatelog">Modifier mon login/mot de passe</a>
</section>

<script src="js/delete.ajax.js"></script>