<section id ="admin-add-event">
    <div class="admin-menu">
        <a href="admin.php"><i class="fas fa-angle-double-left"></i>Menu Admin</a>
    </div>
    <?php if(array_key_exists('update_id', $_GET)) :?>
        <h1 class="title">Modifier un événement</h1>
        <form method="post" action="">
            <ul>
                <div>
                    <!-- Selecteur de date --> 
                    <li>
                        <label for"appointementdate">Date de l'événement&nbsp;:</label>
                        <div class="select-date">
                            <select name="day">
                                <option value="<?= $newsEventsUpdate['eventday']?>"><?= $newsEventsUpdate['eventday']?></option>
                                <?php for ($day = 1; $day <= 31; $day++): ?>
                                    <option value="<?= sprintf("%02d",$day) ?>"><?= sprintf("%02d",$day) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="month">
                                <option value="<?= $newsEventsUpdate['eventmonth']?>"><?= $newsEventsUpdate['eventmonth']?></option>
                                <?php for ($month = 1; $month <= 12; $month++): ?>
                                    <option value="<?= sprintf("%02d",$month) ?>"><?= sprintf("%02d",$month) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="year">
                                <option value="<?= $newsEventsUpdate['eventyear']?>"><?= $newsEventsUpdate['eventyear']?></option>
                                <?php for ($year = date("Y"); $year <=  date("Y") + 3 ; $year++):  ?>
                                    <option value="<?=$year ?>"><?=$year ?></option>
                                <?php endfor ?>
                            </select>
                        </div>
                    </li>
                    <!-- Sélecteur d'heure de début-->
                    <li>
                        <label for"appointementtime">Heure de rendez-vous&nbsp;:</label>
                        <div class="select-time">
                            <select name="appointementhour">
                                <option value="<?= $newsEventsUpdate['eventhour']?>"><?= $newsEventsUpdate['eventhour']?></option>
                                <?php for ($hour = 0; $hour <= 23; $hour++): ?>
                                    <option value="<?= sprintf("%02d",$hour) ?>"><?= sprintf("%02d",$hour) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="appointementminutes">
                                <option value="<?= $newsEventsUpdate['eventminutes']?>"><?= $newsEventsUpdate['eventminutes']?></option>
                                <?php for ($minutes = 0; $minutes <= 59; $minutes++): ?>
                                    <option value="<?= sprintf("%02d",$minutes); ?>"><?= sprintf("%02d",$minutes); ?></option>
                                <?php endfor ?>
                            </select>
                        </div>
                    </li>
                    <!-- Sélecteur d'heure de fin-->
                    <li>
                        <label for"endtimeevent">Heure de fin&nbsp;:</label>
                        <div class="select-time">
                            <select name="endtimehour">
                                <option value=""></option>
                                <?php for ($hour = 0; $hour <= 23; $hour++): ?>
                                    <option value="<?= sprintf("%02d",$hour) ?>"><?= sprintf("%02d",$hour) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="endtimeminutes">
                                <option value=""></option>
                                <?php for ($minutes = 0; $minutes <= 59; $minutes++): ?>
                                    <option value="<?= sprintf("%02d",$minutes); ?>"><?= sprintf("%02d",$minutes); ?></option>
                                <?php endfor ?>
                            </select>
                        </div>
                    </li>
                    <!-- Ville-->
                    <li>
                        <label for="city">Ville&nbsp;:</label>
                        <input id="city" type="text" value="<?= $newsEventsUpdate['city']?>" name="city" data-name="Ville" data-type="alphanum">
                    </li>
                    <!-- Type d'événement -->
                    <li>
                        <label for="eventtype">Type d'événement&nbsp;:</label>
                        <input id="eventtype" type="text" value="<?= $newsEventsUpdate['eventtype']?>" name="eventtype" data-name="TypeEvenement" data-type="alphanum">
                    </li>
                </div>
                <!-- Description de l'événement-->
                <li>
                    <label for="eventdescription">Description&nbsp;:</label>
                    <textarea id="eventdescription" type="text" name="eventdescription" data-required data-name="DescriptionEvenement" data-type="alphanum"><?= $newsEventsUpdate['eventdescription']?></textarea>
                </li>
                <!-- Utilisation d'un champ caché pour récupérer l'id de la newsevents à changer -->
                <input type="hidden" name="id" value="<?= $newsEventsUpdate['id']?>">
            </ul>
            <!-- bouton Mise a jour-->
            <button class="add-event-btn" type="submit" name="updateEvent"><i class="fas fa-plus"></i>Modifier l'événement </button>
            <button class="add-event-btn" type="reset" name="reset" value="effacer"><i class="fa fa-trash"></i>Rétablir l'événement </button>
            <button class="add-event-btn" type="submit" name="delete_id"><i class="fa fa-trash"></i>Supprimer l'événement</button>
        </form>
    <?php else: ?>
        <h1 class="title">Ajouter un événement</h1>
        <form method="post" action="">
            <ul>
                <div>
                    <!-- Selecteur de date --> 
                    <li>
                        <label for"appointementdate">Date de l'événement&nbsp;:</label>
                        <div class="select-date">
                            <select name="day">
                                <option value=""></option>
                                <?php for ($day = 1; $day <= 31; $day++): ?>
                                    <option value="<?= sprintf("%02d",$day) ?>"><?= sprintf("%02d",$day) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="month">
                                <option value=""></option>
                                <?php for ($month = 1; $month <= 12; $month++): ?>
                                    <option value="<?= sprintf("%02d",$month) ?>"><?= sprintf("%02d",$month) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="year">
                                <option value=""></option>
                                <?php for ($year = date("Y"); $year <=  date("Y") + 3 ; $year++):  ?>
                                    <option value="<?=$year ?>"><?=$year ?></option>
                                <?php endfor ?>
                            </select>
                        </div>
                    </li>
                    <!-- Sélecteur d'heure de début-->
                    <li>
                        <label for"appointementtime">Heure de rendez-vous&nbsp;:</label>
                        <div class="select-time">
                            <select name="appointementhour">
                                <option value=""></option>
                                <?php for ($hour = 0; $hour <= 23; $hour++): ?>
                                    <option value="<?= sprintf("%02d",$hour) ?>"><?= sprintf("%02d",$hour) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="appointementminutes">
                                <option value=""></option>
                                <?php for ($minutes = 0; $minutes <= 59; $minutes++): ?>
                                    <option value="<?= sprintf("%02d",$minutes); ?>"><?= sprintf("%02d",$minutes); ?></option>
                                <?php endfor ?>
                            </select>
                        </div>
                    </li>
                    <!-- Sélecteur d'heure de fin-->
                    <li>
                        <label for"endtimeevent">Heure de fin&nbsp;:</label>
                        <div class="select-time">
                            <select name="endtimehour">
                                <option value=""></option>
                                <?php for ($hour = 0; $hour <= 23; $hour++): ?>
                                    <option value="<?= sprintf("%02d",$hour) ?>"><?= sprintf("%02d",$hour) ?></option>
                                <?php endfor ?>
                            </select>
                            <select name="endtimeminutes">
                                <option value=""></option>
                                <?php for ($minutes = 0; $minutes <= 59; $minutes++): ?>
                                    <option value="<?= sprintf("%02d",$minutes); ?>"><?= sprintf("%02d",$minutes); ?></option>
                                <?php endfor ?>
                            </select>
                        </div>
                    </li>
                    <!-- Ville-->
                    <li>
                        <label for="city">Ville&nbsp;:</label>
                        <input id="city" type="text" value="" name="city" data-name="Ville" data-type="alphanum">
                    </li>
                    <!-- Type d'événement -->
                    <li>
                        <label for="eventtype">Type d'événement&nbsp;:</label>
                        <input id="eventtype" type="text" value="" name="eventtype" data-name="TypeEvenement" data-type="alphanum">
                    </li>
                </div>
                <!-- Description de l'événement-->
                <li>
                    <label for="eventdescription">Description&nbsp;:</label>
                    <textarea id="eventdescription" type="text" name="eventdescription" data-required data-name="DescriptionEvenement" data-type="alphanum"></textarea>
                </li>
            </ul>
            <!-- bouton Ajouter-->
            <button class="add-event-btn" type="submit" name="addEvent"><i class="fas fa-plus"></i>Ajouter l'événement</button>
            <button class="add-event-btn" type="reset" name="reset" value="effacer"><i class="fa fa-trash"></i>Effacer</button>
        </form>
    <?php endif;?>
    <div class="admin-menu">
        <a href="admin.php"><i class="fas fa-angle-double-left"></i>Menu Admin</a>
    </div>
</section>