<section id="aloe-vera">
    <article class="aloe-description">
        <h1 class="title">L'Aloe Vera</h1>
        <img src="img/aloeVera8.jpg" alt="Plante d'Aloe Vera">

        <p>L’Aloe vera est connu depuis des millénaires pour ses multiples vertus et sa richesse en composants actifs. Plus de 250 constituants d’intérêt ont été identifiés, dont des vitamines (A, B, C et E des minéraux (zinc, cuivre et fer), des sucres (glucose, mannose et cellulose), des lipides et des glycoprotéines.
        </p>
        
        <img src="img/aloeVera7.jpg" alt="Plante d'Aloe Vera">
        <p>De nombreuses études ont démontré l’efficacité de cette merveille botanique, aussi bien en utilisation interne qu’externe. En application topique, l’Aloe Vera possède un fort pouvoir hydratant, et facilite la cicatrisation. Il contribue au renouvellement de la peau par son action sur la prolifération des kéranocytes et la synthèse du collagène de type I. De plus, il hydrate, apaise et régénère l’épiderme.
        </p>
        
        <img src="img/aloeVera2.jpg" alt="Plante d'Aloe Vera">
        <p>En utilisation interne, l’Aloe Vera constitue un excellent complément alimentaire du fait de sa richesse en molécules anti-oxydantes. Il contribue à renforcer les défenses naturelles de l’organisme et a un effet bénéfique en cas de fatigue physique et psychique.
        </p>

    </article>
    <article class="reasons">
        <h2 class="title">10 Bonnes raisons de boire la pulpe d'Aloe Vera</h2>
        <ol>
            <li><p>Stimulant pour les défenses naturelles de l’organisme.</p> La pulpe d’Aloe Vera stabilisée contient tous les actifs naturels de la plante. L’Aloe Vera aide à stimuler les défenses naturelles de notre organisme pour lutter contre les micro-organismes.</li>
            <li><p>Apporte du bien-être en cas de fatigue passagère.</p> La pulpe d’Aloe Vera stabilisée permet de se sentir mieux au quotidien.</li>
            <li><p>Renferme des antioxydants.</p> L’eau végétale intacte contenue dans la pulpe d’Aloe Vera stabilisée apporte des antioxydants à notre organisme au quotidien.</li>
            <li><p>Aide à se protéger contre les radicaux libres.</p> La pulpe d’Aloe Vera stabilisée nous aide ainsi à nous défendre contre le stress oxydant.</li>
            <li><p>Contribue au maintien d’une peau normale.</p> La pulpe d’Aloe Vera stabilisée agit à ce niveau. Notre peau devient plus souple et plus hydratée.</li>
            <li><p>Aide au maintien d’une ossature normale.</p> La pulpe d’Aloe Vera stabilisée aide au maintien d’une charpente osseuse normale.</li>
            <li><p>Permet d’augmenter son hydratation au quotidien.</p> L’eau végétale de la plante permet aussi d’augmenter notre apport hydrique.</li>
            <li><p>Apporte de la vitamine C.</p> La pulpe d’Aloe Vera stabilisée contient de la vitamine C et complète ainsi nos apports quotidiens.</li>
            <li><p>Apporte tous les bienfaits de la plante.</p> La synergie de tous les nutriments contenus dans la pulpe d'Aloe Vera apporte à l'organisme tout ce dont il a besoin pour bien fonctionner.</li>
            <li><p>Peut être consommée tous les jours.</p> Boire la pulpe d'Aloe Vera pure et diluée à raison de 60 à 90 ml / jour.</li>
        </ol>
    </article>
</section>