<section id="page-error">
    <div>
        <div>
            <h1 class="oups">OUPS !!!!</h1>
            <p class="oups">ERREUR 500</p>
        </div>
        <div class='page-error-second-div'>
            <img src="img/panneau.jpg" alt="Panneau de direction Aloe Vera">
            <div>
                <p class="page-error-msg"> Une erreur s'est produite !</p>
                <a href="home" class="admin-a-btn">Retour à l'accueil</a>
                <a href="#" class="admin-a-btn previous-page">Page précédente</a>
            </div>
        </div>
    </div>
</section>