<?php include 'nextEvent.phtml' ?>

<section id="home">
    <section id="articles">
        <article class="whoiam">
            <p class="title">Qui suis-je?</p>
            <img src="img/aloeVera.jpg" alt="Plant d'Aloé Véra">
            <h1 class="identity">Laurence Boussin <br/>Entrepreneur FOREVER</h1>
            <p>Je m'appelle Laurence Boussin et je suis Manager Adjoint, entrepreneur Forever, partenaire de Forever Living Products.
            Je suis située au Theil de Bretagne dans le sud-est de l'Ille-et-Vilaine à seulement 20 minutes de Rennes sur la route d'Angers. J'exerce cette fonction depuis 2011. Je me déplace à votre domicile ou suis présente à certains événements.
            A travers ce site internet, vous pourrez retrouver <a href="#news-events">mes actualités</a>, <a href="products">les produits</a> que nous proposons, les démarches concernant <a href="sponsorship">le parrainage</a> ainsi qu'une page concernant les bienfaits de l'<a href="aloevera">Aloé&nbsp;Véra</a>. Si vous avez des questions ou souhaitez prendre RDV, n'hésitez pas à me contacter en remplissant ce <a href="contact">formulaire de contact.</a>
            </p>
        </article>

        <article class="history">
            <h2 class="title">Notre Histoire</h2>
            <img src="img/rexMaughan.jpg" alt="Rex Maughan-Fondateur FOREVER">
            <p class="identity">Rex Maughan, fondateur de Forever Living Products</p>
            <p>Rex Maughan souhaitait promouvoir le bien-être pour tous. Il a donc créé en 1978 FOREVER LIVING PRODUCTS, afin de partager les exceptionnels bienfaits de l’Aloe vera tout autour du monde. Depuis le premier jour, il s’est engagé à trouver les ingrédients issus des meilleures sources, et à travailler avec des experts, afin de proposer des produits d’une qualité irréprochable. Aujourd’hui, les produits de FOREVER LIVING PRODUCTS sont commercialisés à travers le monde, uniquement par l’intermédiaire d’Entrepreneurs Indépendants (FBO, Forever Business Owner). L’entreprise compte des millions de FBO dans plus de 158 pays.
            </p>
        </article>
    </section>
    <aside id="news-events">
        <h3 class="title-news">News & Evénements : </h3>
        <?php if(count($newsEvents) == 0) : ?>
            <p class="no-event">Il n'y a pas d'événement prochainement ! </p>
        <?php else :?>
            <?php foreach($newsEvents as $newsEvent): ?>
                <ul>
                    <?php if( $newsEvent['eventday'] != null && $newsEvent['eventmonth'] != null && $newsEvent['eventyear'] != null && $newsEvent['eventtime'] != null && $newsEvent['eventtype'] != null && $newsEvent['city'] != null) :?>
                        <li>Le <span><?= $newsEvent['eventday']?> <?= $months[($newsEvent['eventmonth'])-1]?> <?= $newsEvent['eventyear']?></span>
                            <?php if( $newsEvent['endtime'] != null) :?>
                                de <span><?= $newsEvent['eventtime']?></span> à <span><?= $newsEvent['endtime']?></span>
                            <?php else :?>
                                dès <span><?= $newsEvent['eventtime']?></span>
                            <?php endif ?>
                        </li>

                        <?php if(stripos($newsEvent['city'], 'le') === 0 ) : ?>
                            <li><span><?= $newsEvent['eventtype'];?></span> au <span><?= substr($newsEvent['city'],3);?></span></li>
                        <?php else: ?>
                            <li><span><?= $newsEvent['eventtype'];?></span> à <span><?= $newsEvent['city'];?></span></li>
                        <?php endif;?>
                        
                        <?php if($newsEvent['eventdescription'] != null) : ?>
                            <li><?= $newsEvent['eventdescription']?></li>
                        <?php endif;?>
                        
                    <?php else :?>
                        <li><?= $newsEvent['eventdescription']?></li>
                    <?php endif ?>
                </ul>
            <?php endforeach; ?>
        <?php endif;?>
    </aside>
</section>
