<?php include 'nextEvent.phtml' ?>

<section id="home">
    <section id="articles">
        <article class="whoiam">
            <p class="title">Qui suis-je?</p>
            <img src="img/aloeVera.jpg" alt="Plant d'Aloé Véra">
            <h1 class="identity">Laurence Boussin<br/>Entrepreneur FOREVER</h1>
            <p>Je m'appelle Laurence Boussin et je suis FBO (Forever Business Owner), entrepreneur Forever, partenaire de Forever Living Products.
            Je suis situé au Theil de Bretagne dans le sud-est de l'Ille-et-Vilaine à seulement 20 minutes de Rennes sur la route d'Angers. J'exerce cette fonction depuis .... Je me déplace à votre domicile ou suis présente à certains événements.
            A travers ce site internet, vous pourrez retrouver <a href="#news-events">mes actualités</a>, <a href="products.php">les produits</a> que nous proposons, les démarches concernant <a href="sponsorship.php">le parrainage</a> ainsi qu'une page concernant les bienfaits de l'<a href="aloevera.php">Aloé&nbsp;Véra</a>. Si vous avez des questions ou souhaitez prendre RDV, n'hésitez pas à me contacter en remplissant ce <a href="contact.php">formulaire de contact.</a>
            </p>
        </article>

        <article class="history">
            <h2 class="title">Notre Histoire</h2>
            <img src="img/rexMaughan.jpg" alt="Rex Maughan-Fondateur FOREVER">
            <p class="identity">Rex Maughan, fondateur de Forever Living Products</p>
            <p>Rex Maughan souhaitait promouvoir le bien-être pour tous.Il a donc créé en 1978 FOREVER LIVING PRODUCTS, afin de partager les exceptionnels bienfaits de l’Aloe vera tout autour du monde. Depuis le premier jour, il s’est engagé à trouver les ingrédients issus des meilleures sources, et à travailler avec des experts, afin de proposer des produits d’une qualité irréprochable. Aujourd’hui, les produits de FOREVER LIVING PRODUCTS sont commercialisés à travers le monde, uniquement par l’intermédiaire d’Entrepreneurs Indépendants (FBO, Forever Business Owner). L’entreprise compte des millions de FBO dans plus de 158 pays.
            </p>
        </article>
    </section>
    <aside id="news-events">
        <h3 class="title-news">News & Evénements : </h3>
        <?php foreach($newsevents as $newsevent): ?>
            <ul>
                <li>Le <?= $newsevent['day'] . '/' . $newsevent['month']. '/' . $newsevent['year']?> à <?= $newsevent['hour'] . 'h' . $newsevent['minute']?> </li>
                <li class="<?= $newsevent['city']?>">A <?= substr($newsevent['city'],0,2);?></li>
                <li><?= $newsevent['eventdescription']?></li>
            </ul>
        <?php endforeach; ?>
        <!-- <ul>
            <li>Le 24.04.2018 de 9h a 18h</li>
            <li>Au Theil de Bretagne</li>
            <li>Je serai presente sur le place de la mairie a mon stand FOREVER</li>
        </ul>
        <ul>
            <li>Le 24.04.2018 de 9h a 18h</li>
            <li>Au Theil de Bretagne</li>
            <li>Je serai presente sur le place de la mairie a mon stand FOREVER</li>
        </ul>
        <ul>
            <li>Le 24.04.2018 de 9h a 18h</li>
            <li>Au Theil de Bretagne</li>
            <li>Je serai presente sur le place de la mairie a mon stand FOREVER</li>
        </ul> -->
    </aside>
</section>