<section class="next-event">
    <div class="title-event">
        <img src="img/tape1.png" alt="ruban adhésif">
        <p>Prochains événements&nbsp;:</p>
    </div>
    <div class="slider-events">
        <img src="img/tape2.png" alt="ruban adhésif">
        <div class="bg-slider">
            <?php foreach($newsEvents as $newsEvent): ?>
                <p><?= $newsEvent['eventdescription']?></p>
            <?php endforeach; ?>
            <!-- <p>Je serai présente sur le place de la mairie à mon stand FOREVER</p>
            <p>Retrouvez-moi à mon stand Forever dès 9h du matin</p>
            <p>On se retrouve à mon stand FOREVER</p>
            <p>stand Forever présent ce jour là</p> -->
        </div>
        <img src="img/tape3.png" alt="ruban adhésif">
    </div>
</section>

<script src="js/slider.js"></script>