<section class="next-event">
    <div class="title-event">
        <img src="img/tape1.png" alt="ruban adhésif">
        <p>Prochains événements&nbsp;:</p>
    </div>
    <div class="slider-events">
        <img src="img/tape2.png" alt="ruban adhésif">
        <div class="bg-slider">
            <p>Brocante du Theil le dimanche 22 avril 2018</p>
        </div>
        <img src="img/tape3.png" alt="ruban adhésif">
    </div>
</section>

<script src="js/slider.js"></script>