<?php include 'nextEvent.phtml' ?>

<section id="products">
    <h1 class="title">Les&nbsp;Indispensables FOREVER</h1>
    <nav>
        <a href="#health">Santé</a>
        <a href="#pain">Douleur</a>
        <a href="#skin">Peau</a>
        <a href="#daily">Quotidien</a>
        <a href="#house-animals">Maison Animaux</a>
        <a href="pdf/foreverCatalogue2018.pdf" target="blank">Catalogue FOREVER</a>
    </nav>
    <section id="health">
        <h2 class="first-title">Santé&nbsp;:</h2>
        <div class="products-container">
            <article>
                <h3>Pulpe d'Aloe Vera TetraPak</h3>
                <img src="img/products/715.png" alt="Pulpe d'Aloe Vera TetraPak">
                <a href="product.php#product">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Forever Bee Propolis</h3>
                <img src="img/products/27.png" alt="Forever Bee Propolis">
                <a href="">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Forever Royal Jelly</h3>
                <img src="img/products/36.png" alt="Forever Royal Jelly">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>
        </div>        
    </section>

    <section id="pain">
        <h2>Douleur&nbsp;:</h2>
        <div class="products-container">
            <article>
                <h3>Emulsion Thermogène - Aloe Heat Lotion</h3>
                <img src="img/products/64.png" alt="Emulsion Thermogène - Aloe Heat Lotion">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Aloe MSM Gel</h3>
                <img src="img/products/205.png" alt="Aloe MSM Gel">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>
        </div>       
    </section>

    <section id="skin">
        <h2>Peau&nbsp;:</h2>
        <div class="products-container">
            <article>
                <h3>Gelée d'aloès</h3>
                <img src="img/products/61.png" alt="Gelée d'aloès">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Aloe Propolis Crème</h3>
                <img src="img/products/51.png" alt="Aloe Propolis Crème">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Crème Visage Aloès</h3>
                <img src="img/products/63.png" alt="Crème Visage Aloès">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Soin Hydratant Intense Sonya</h3>
                <img src="img/products/311.png" alt="Soin Hydratant Intense Sonya">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Sérum Nourrissant au Thé Blanc Sonya</h3>
                <img src="img/products/281.png" alt="Sérum Nourrissant au Thé Blanc Sonya">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>
        </div>       
    </section>

    <section id="daily">
        <h2>Quotidien&nbsp;:</h2>
        <div class="products-container">
            <article>
                <h3>Stick Déodorant Aloès</h3>
                <img src="img/products/67.png" alt="Stick Déodorant Aloès">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Forever Bright Toothgel</h3>
                <img src="img/products/28.png" alt="Forever Bright Toothgel">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>

            <article>
                <h3>Aloé Lèvres</h3>
                <img src="img/products/1022.png" alt="Aloé Lèvres">
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </article>
        </div>       
    </section>

    <section id="house-animals">
        <h2>Maison & Animaux :</h2>
        <p>Il existe une gamme de produits "Maison & Animaux" mais aussi beaucoup d'autres produits que vous pouvez consulter <a href="pdf/foreverCatalogue2018.pdf" target="blank">ici dans ce catalogue.</a></p>
        <p>Si vous avez des questions, n'hésitez pas à me contacter <a href="contact.php">ici sur ma page de Contact</a></p>

    </section>
</section>