<!-- si l'utilisateur a cliqué sur "envoyer" et qu'une erreur existe, ou "true" (dans le cas de l'arrivée de l'utilisateur sur la page on affiche tout simplement le formualire SANS le message d'erreur) -->
<?php if(array_key_exists('addComment',$_POST) && $errorModel->getErrorMessage() != null):?>

    <?php if($errorModel->getErrorMessage() != null):?>
        <!-- affichage du message d'erreur s'il existe (VALABLE UNIQUEMENT SI LE JS EST DESACTIVE) -->
        <aside class="error-message">
            <!-- affichage du message d'erreur s'il existe (VALABLE UNIQUEMENT SI LE JS EST DESACTIVE) -->
            <ul>
                <li><?=$errorModel->getErrorMessage();?></li>
            </ul>
        </aside>
    <?php endif;?>
<?php else:?>
<!-- En cas d'absence d'erreur on affiche bien "Les prochains événements"-->
    <?php include 'nextEvent.phtml' ?>
<?php endif;?>

<section id="product" class="<?=$productsById['categoryforcss']?>">

    <h1 class="title"><?=$productsById['title']?></h1>
    <div class="div-description">
        <img src="img/products/<?=$productsById['ref']?>.png" alt="<?=$productsById['title']?>">
        <div class="description">
            <p><?=$productsById['productdescription']?></p>
            <p><span>Catégorie</span> : <?=$productsById['category']?></p>
            <p><span>Contenance</span> : <?=$productsById['capacity']?></p>
            <p><span>Composition</span> : <?=$productsById['composition']?></p>
            <p><span>Référence</span> : <?=$productsById['ref']?></p>
        </div>
    </div>
    <div class="return">
        <a href="products.php#<?=$productsById['categoryforcss']?>"><i class="fas fa-angle-double-left"></i> Retour aux Produits</a>
    </div>

    <form id="form" method="POST" action="">
        <!-- Si l'utilisateur a cliqué sur "envoyer le commentaire" et qu'aucune erreur n'existe, 
        on l'informe que son commentaire a bien été ajouté (VALABLE AVEC OU SANS JS)-->
        <?php if((array_key_exists('addComment',$_POST) && $errorModel->getErrorMessage() == null )) : ?>
            <div class="div-commentary-inform">
                <p class="commentary-inform">Votre Commentaire a bien été ajouté&nbsp;!</p>
            </div>
        <?php else :?>
            <?php if($comments == null) :?>
                <div class="div-commentary-inform">
                    <p class="commentary-inform">Aucun commentaire au sujet de <?=$productsById['title']?> n'a été ajouté.</br><span>Soyez le/la premier(e)&nbsp;! </span></p>
                </div>
            <?php endif; ?>

            <!-- aside, avec la class="error-message", qui permet l'affichage des erreurs grace au JAVASCRIPT -->
            <aside class='error-message hidden'></aside>
            
            <fieldset>
                <legend>Ajouter un commentaire</legend>
                <ul>
                    <!--E mail-->
                    <li>
                        <label for="email">E-mail <span class="required">*</span></label>
                        <input id="email" type="text" value="<?php if(isset($email)){echo htmlspecialchars($email);}?>" name="email" data-required data-name="E-mail" data-type="email">
                    </li>

                    <!--Pseudo-->
                    <li>
                        <label for="pseudo">Pseudo <span class="required">*</span></label>
                        <input id="pseudo" type="text" value="<?php if(isset($pseudo)){echo htmlspecialchars($pseudo);}?>" name="pseudo" data-required data-name="Pseudo" data-type="alphanum">
                    </li>
                    <!-- Satisfaction -->
                    <li>
                        <label for"satisfaction">Votre avis <span class="required">*</span></label>
                        <select id="satisfaction" data-required data-name="Satisfaction" name="satisfaction">
                            <option><?php if(isset($satisfaction)){echo htmlspecialchars($satisfaction);}?></option>
                            <option value="Pas satisfait(e)">Pas satisfait(e)</option>
                            <option value="Peu satisfait(e)">Peu satisfait(e)</option>
                            <option value="Assez satisfait(e)">Assez satisfait(e)</option>
                            <option value="Très satisfait(e)">Très satisfait(e)</option>
                            <option value="Exceptionnel">Exceptionnel</option>
                        </select>
                    </li>
                    <!-- Commentaire -->
                    <li>
                        <label for="usercomment">Message<span class="required">*</span></label>
                        <textarea id="usercomment" placeholder="Ici, votre commentaire !" type="text" name="usercomment" data-name="Commentaire" data-required><?php if(isset($userComment)){echo htmlspecialchars($userComment);}?></textarea>
                    </li>
                </ul>
                <p class="italic"><span class="required">*</span> Ces champs sont obligatoires !</p>
                
                <!-- Utilisation d'un champ caché pour récupérer l'id de la newsevents à changer -->
                <input type="hidden" name="refproduct" value="<?=$productsById['ref']?>">

                <!-- bouton enregistrer-->
                <input class="submit-btn" type="submit" id="submit" name="addComment" value="Envoyer">
            </fieldset>
        <?php endif; ?>

    </form>

    <?php if($comments != null) : ?>
        <div class="return">
            <button type="button" id="showComments" data-comments="<?=$productsById['ref']?>">Voir les commentaires sur <?=$comments['0']['title']?></br><i class="fas fa-angle-double-down"></i></button>

            <button type="button" id="hideComments" data-comments="<?=$productsById['ref']?>">Masquer les commentaires sur <?=$comments['0']['title']?></br><i class="fas fa-angle-double-up"></i></button>
        </div>

        <div id="comments-title">
            <h2 class="comments-title"> Les commentaires sur <?=$comments['0']['title']?></h2>
            <p class="refproduct">Référence produit : <?=$comments['0']['refproduct']?></p>
        </div>

        <p id="target"></p>

    <?php endif;?>

</section>

<script src="js/product_com.ajax.js"></script>