<section id="products">
    <h1 class="title">Les&nbsp;Indispensables FOREVER</h1>

    <section class="health">
        <h2 class="first-title">Santé :</h2>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Pulpe</figcaption>
                    <img src="img/products/15.png" alt="Pulpe">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Une formule nourrissante et protectrice pour ce baume à lèvres qui associe Aloe Vera, huile de jojoba et cire d'abeille. Il apporte un confort revitalisant pour les lèvres les plus desséchées. * Hydratation des couches supérieures de l'épiderme </p>
                <p><span>Contenance :</span>  4.5g</p>
                <p><span>Composition :</span>  27.6 % de gel d'aloès, 20.4 % d'huile de jojoba. </p>
                <p><span>Référence :</span>  1022</p>
            </div>
        </article>
    </section>

    <section class="pain">
        <h2>Douleur :</h2>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Heat</figcaption>
                    <img src="img/products/64.png" alt="Heat">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Une formule nourrissante et protectrice pour ce baume à lèvres qui associe Aloe Vera, huile de jojoba et cire d'abeille. Il apporte un confort revitalisant pour les lèvres les plus desséchées. * Hydratation des couches supérieures de l'épiderme </p>
                <p><span>Contenance :</span>  4.5g</p>
                <p><span>Composition :</span>  27.6 % de gel d'aloès, 20.4 % d'huile de jojoba. </p>
                <p><span>Référence :</span>  1022</p>
            </div>
        </article>
    </section>

    <section class="skin">
        <h2>Peau :</h2>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Gelée d'aloès</figcaption>
                    <img src="img/products/61.png" alt="Gelée d'aloès">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Particulièrement riche en Aloe Vera, ce gel transparent non gras possède toutes les vertus de la plante. Il hydrate*, apaise et régénère l'épiderme. Il est idéal contre les irritations de la peau et les coups de soleil. * Hydratation des couches supérieures de l'épiderme </p>
                <p><span>Contenance :</span>118 ml</p>
                <p><span>Composition :</span>84.46 % de gel d'aloès.</p>
                <p><span>Référence :</span>61</p>
            </div>
        </article>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Aloe Propolis Crème</figcaption>
                    <img src="img/products/51.png" alt="Aloe Propolis Crème">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>L'aloès associé à la propolis, font de cette crème à la texture riche, un véritable soin anti-bactérien et réparateur, qui apaise les irritations cutanées. La camomille, l'allantoïne et les vitamines A et E apportent à la peau douceur et souplesse. Elle peut être utilisée sur les peaux sèches et rugueuses. </p>
                <p><span>Contenance :</span>113g</p>
                <p><span>Composition :</span>74.17 % de gel d'aloès, 0.55 % de propolis</p>
                <p><span>Référence :</span>51</p>
            </div>
        </article>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Crème Visage Aloès</figcaption>
                    <img src="img/products/63.png" alt="Crème Visage Aloès">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Ce soin protège, nourrit et réduit les signes du vieillissement cutané. Sa texture fondante, enrichie en collagène et en élastine, hydrate* et raffermit. La peau est souple, douce et apparaît comme "liftée". Convient aux peaux sensibles. </p>
                <p><span>Contenance :</span>118ml</p>
                <p><span>Composition :</span>36.5 % de gel d'aloès.</p>
                <p><span>Référence :</span>63</p>
            </div>
        </article>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Soin Hydratant Intense Sonya</figcaption>
                    <img src="img/products/311.png" alt="Soin Hydratant Intense Sonya">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Ce soin régénérant agit comme un bain d'hydratation* et procure à la peau un confort. La peau est raffermie, paraît visiblement plus jeune et lissée. Les rides et ridules sont visiblement réduites apportant confort et tonus tout au long de la journée. * Hydratation des couches supérieures de l'épiderme. FORMULE OPTIMISÉE</p>
                <p><span>Contenance :</span>71g</p>
                <p><span>Composition :</span>26 % de gel d'aloès.</p>
                <p><span>Référence :</span>311</p>
            </div>
        </article>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Sérum Nourrissant au Thé Blanc Sonya</figcaption>
                    <img src="img/products/281.png" alt="Sérum Nourrissant au Thé Blanc Sonya">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Ce sérum apporte souplesse et préserve l'élasticité de la peau tout en l'hydratant* intensément. Il réduit les signes visibles du vieillissement cutané. Sa texture riche et légèrement gélifiée pénètre en profondeur et laisse un confort intense. * Hydratation des couches supérieures de l'épiderme.</p>
                <p><span>Contenance :</span>118ml</p>
                <p><span>Composition :</span>37 % de gel d'aloès.</p>
                <p><span>Référence :</span>281</p>
            </div>
        </article>
    </section>

    <section class="daily">
        <h2>Quotidien :</h2>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Stick Déodorant Aloès</figcaption>
                    <img src="img/products/67.png" alt="Stick Déodorant Aloès">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Sans alcool, sans sels d'aluminium et discrètement parfumé, ce déodorant assure une protection efficace sans tacher vos vêtements. Sa formule à l'aloès adoucit et hydrate* la peau. *Hydrate les couches supérieures de l'épiderme. </p>
                <p><span>Contenance :</span>92.1g</p>
                <p><span>Composition :</span>Gel d'aloès.</p>
                <p><span>Référence :</span>67</p>
            </div>
        </article>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Forever Bright Toothgel</figcaption>
                    <img src="img/products/28.png" alt="Forever Bright Toothgel">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Ce gel dentaire, sans fluor et non abrasif, ravive la blancheur de vos dents. Son complexe à la chlorophylle, sans menthol, procure une sensation de fraîcheur naturelle. Sa formule complète à base de propolis et d'aloès aide à préserver votre l'hygiène buccale. </p>
                <p><span>Contenance :</span>130g</p>
                <p><span>Composition :</span>35.5 % de gel d'aloès.</p>
                <p><span>Référence :</span>28</p>
            </div>
        </article>

        <article>
            <div class="img-product">
                <figure>
                    <figcaption>Aloé Lèvres</figcaption>
                    <img src="img/products/1022.png" alt="Aloé Lèvres">
                </figure>
                <a href="#">Description du produit <i class="fas fa-plus-square"></i></a>
            </div>

            <div class="description hidden">
                <p>Une formule nourrissante et protectrice pour ce baume à lèvres qui associe Aloe Vera, huile de jojoba et cire d'abeille. Il apporte un confort revitalisant pour les lèvres les plus desséchées. * Hydratation des couches supérieures de l'épiderme </p>
                <p><span>Contenance :</span>4.5g</p>
                <p><span>Composition :</span>27.6 % de gel d'aloès, 20.4 % d'huile de jojoba.</p>
                <p><span>Référence :</span>1022</p>
            </div>
        </article>
    </section>

    <section class="house-animals">
        <h2>Maison & Animaux :</h2>
        <p>Il existe une gamme de produits "Maison & Animaux" mais aussi beaucoup d'autres produits que vous pouvez consulter <a href="pdf/foreverCatalogue2018.pdf" target="blank">ici dans ce catalogue.</a></p>
        <p>Si vous avez des questions, n'hésitez pas à me contacter <a href="contact.php">ici sur ma page de Contact</a></p>

    </section>

</section>