<?php include 'nextEvent.phtml' ?>

<section id="product">
    <h1 class="title">Pulpe d'Aloès Stabilisée</h1>
    <div>
        <img src="img/products/15.png" alt="Pulpe d'Aloès Stabilisée">
        <div class="description">
            <p>Premier produit Forever à avoir obtenu le label du IASC (Conseil International scientifique de l’Aloe Vera), la Pulpe d’Aloès Stabilisée est le produit à utiliser quotidiennement pour conserver un bien-être optimal. L’Aloe Vera contribue au maintien du système immunitaire. Elle possède de puissants antioxydants qui aident à renforcer les défenses de l’organisme. Elle stimule le métabolisme et a un effet bénéfique en cas de fatigue.</p>
            <p><span>Catégorie</span> : Santé</p>
            <p><span>Contenance</span> : 1L</p>
            <p><span>Composition</span> : 96.28 % de pulpe d'Aloe Vera stabilisée</p>
            <p><span>Référence</span> : 15</p>
        </div>
    </div>
</section>