<?php include 'nextEvent.phtml' ?>

<section id="sponsorship">
    <h1 class="title">Devenir Distributeur indépendant FOREVER</h1>
        <img src="img/aloeVera12.2.jpg" alt="image d'Aloe Vera">
    <article class="sale">
        <h2 class="title-small">La Vente :</h2>
        <p>La vente directe peut répondre à votre situation :</p>
        <ul>
            <li>vous devenez indépendant dans une activité valorisante où votre motivation et votre travail feront la différence,</li>
            <li>vous bénéficierez d'une formation gratuire et d'un soutien permanent,</li>
            <li>vous conservez votre indépendance, sans contrainte de réaliser un chiffre d'affaires minimum,</li>
            <li>votre investissement de départ est limité à l'achat de la valise administrative d'une valeur de 35€.</li>
        </ul>
        <p>La vente directe vous propose une activité à temps choisi ou à temps plein, sans limite géographique.</p>
    </article>
    <article class="product-range">
        <h2 class="title-small">La Gamme</h2>
        <p>Les produits naturels et de bien-être sont à base d'Aloe Vera en versions buvables et soins de la peau</p>
        <p>Ces produits exclusifs offrent un excellent rapport qualité/prix. Très efficaces grâce à des pourcentages d'actifs très élevés, consommables et renouvelables, ils fidélisent rapidement la clientèle. Nos produits bénéficient d'(une grantie "Satisfait ou Remboursé" de 30 jours.</p>
        <p>La société FOREVER, créée en 1978, N°1 mondial de l'Aloe Vera, est présente en France depuis 1993.</p>
    </article>
    <article class="status">
        <h2 class="title-small">Le Statut</h2>
        <p>Vendeur Distributeur Indépendant: VDI, reconnu par les pouvoirs publics, présente de nombreux avantages fiscaux et sociaux. Il est compatible avec le régime des retraites, ainsi qu'avec une activité salariée.</p>
        <p>Le plan de rémunération est motivnt. Il est basé sur vos ventes personnelles et sur le chiffre d'affaires de votre groupe.</p>
        <p>La société FOREVER est affiliée à la Fédération de la Vente directe.</p>
        <a href="http://www.fvd.fr/" target="blank"><img src="img/normes/fvd.gif" alt="Fédération de la Vente Directe"></a>
    </article>
    <article class="sponsorship">
        <h2 class="title-small">Vous Parrainer</h2>
        <p>Si vous souhaitez de plus amples informations sur le parrainage pour devenir Distributeur Indépendant FOREVER, veuillez me contacter <a href="contact.php">ici sur le formulaire de contact </a>, je vous répondrai dans les plus brefs délais.</p>
    </article>
</section>