<section id="standards">
    <h1 class="title">Les Normes</h1>
    <article id="iso14001">
        <h2>Iso 14001</h2>
        <img src="img/normes/iso14001.gif" alt="Norme ISO14001">
        <p>Notre système de management environnemental est certifié ISO 14001 : 2004 pour notre respect de l’environnement.</p>
    </article>
    <article id="iso9001">
        <h2>Iso 9001</h2>
        <img src="img/normes/iso9001.gif" alt="Norme ISO9001">
        <p>Notre système de management de la qualité est certifié ISO 9001 : 2008 pour nos produits de qualité constante et garantie.</p>
    </article>
    <article id="certified">
        <h2>Label IASC</h2>
        <img src="img/normes/certified.png" alt="Label IASC (International Aloe Science Council)">
        <p>Nos produits sont les premiers à avoir reçu le label qualité IASC ( International Aloe Science Council ).</p>
    </article>
    <article id="kasher-hallal">
        <h2>Kasher & Hallal</h2>
        <img src="img/normes/kasher.gif" alt="Garantie Kasher">
        <img src="img/normes/halal.gif" alt="Garantie Halal">
        <p>La plupart de nos produits sont garantis Kasher et Halal.</p>
    </article>
    <article id="fvd">
        <h2>Fédération Vente Directe</h2>
        <img src="img/normes/fvd.gif" alt="Fédération de la Vente Directe">
        <p>Nous sommes adhérents à la Fédération de la Vente Directe et avons participé à la création du Code Ethique.</p>
    </article>
</section>